### ISSUE TITLE
GPG key is expired

### ISSUE THREAD

**Issue by robinpaulson** [Shnatsel/cjdns-ubuntu-pubkey#2]
I guess it's this key here:
http://ubuntu.repo.cjdns.ca/

Also, could you package the later updates cjd has published, it's been 4 months since this ppa got an archive?

Cheers

**Comment by Shnatsel** [comment]
Thanks a lot for the report! Will do ASAP

**Comment by Shnatsel** [comment]
Done. Sorry it took so long.

You will have to re-run the command for importing the signing key that's listed in README.md. If you have any issues after that, please let me know.

I had to drop builds for Utopic and Vivid since they are no longer supporetd by Ubuntu. I'll look into adding builds for Wily soon.
